name: Spring Boot CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        -main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: actionsdb
        ports:
          - 3306
        options:
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/actionsdb
          SPRING_DATASOURCE_USERNAME: root